//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPDETAIL
    {
        public int CUSTOMERID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PINCODE { get; set; }
        public Nullable<int> MOBILE { get; set; }
    }
}
