//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_2PRODUCT
    {
        public int PID { get; set; }
        public string PNAME { get; set; }
        public string BRAND { get; set; }
        public int PRICE { get; set; }
        public string DESRIPTION { get; set; }
        public string IMAGE { get; set; }
    }
}
